import '../../model/source.dart';

const madaraVersion = "0.0.11";
const madaraSourceCodeUrl =
    "https://raw.githubusercontent.com/kodjodevf/mangayomi-extensions/main/multisrc/madara/madara-v$madaraVersion.dart";
const defaultDateFormat = "MMMM dd, yyyy";
const defaultDateFormatLocale = "en_US";
List<Source> get madaraSourcesList => _madaraSourcesList;
List<Source> _madaraSourcesList = [
  Source(
      name: "FR-Scan",
      baseUrl: "https://fr-scan.com",
      lang: "fr",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: "fr",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "AstralManga",
      baseUrl: "https://astral-manga.fr",
      lang: "fr",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd/mm/yyyy",
      dateFormatLocale: "fr",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Akuma no Tenshi",
      baseUrl: "https://akumanotenshi.com",
      lang: "tr",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd/MM/yyyy",
      dateFormatLocale: "pt-BR",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Adult Webtoon",
      baseUrl: "https://adultwebtoon.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      isNsfw: true,
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "ArazNovel",
      baseUrl: "https://www.araznovel.com",
      lang: "tr",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "d MMMM yyyy",
      dateFormatLocale: "en",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "BestManga",
      baseUrl: "https://bestmanga.club",
      lang: "ru",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd.MM.yyyy",
      dateFormatLocale: "ru",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Chibi Manga",
      baseUrl: "https://www.cmreader.info",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "CookieToon",
      baseUrl: "https://cookietoon.online",
      lang: "pt-br",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd/MM/yyyy",
      dateFormatLocale: "pt-BR",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Drope Scan",
      baseUrl: "https://dropescan.com",
      lang: "pt-br",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd/MM/yyyy",
      dateFormatLocale: "pt-BR",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "EvaScans",
      baseUrl: "https://evascans.com",
      lang: "tr",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMM d, yyy",
      dateFormatLocale: "tr",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Final Scans",
      baseUrl: "https://finalscans.com",
      lang: "pt-br",
      typeSource: "madara",
      iconUrl: '',
      isNsfw: true,
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: "pt-BR",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Glory Manga",
      baseUrl: "https://glorymanga.com",
      lang: "tr",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd/MM/yyy",
      dateFormatLocale: "tr",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Hentai Manga",
      baseUrl: "https://hentaimanga.me",
      isNsfw: true,
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "HentaiWebtoon",
      baseUrl: "https://hentaiwebtoon.com",
      isNsfw: true,
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Ikifeng",
      baseUrl: "https://ikifeng.com",
      lang: "es",
      typeSource: "madara",
      iconUrl: '',
      isNsfw: true,
      dateFormat: "dd/MM/yyyy",
      dateFormatLocale: "es",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Inmortal Scan",
      baseUrl: "https://manga.mundodrama.site",
      lang: "es",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: "es",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Its Your Right Manhua",
      baseUrl: "https://itsyourightmanhua.com/",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Kami Sama Explorer",
      baseUrl: "https://leitor.kamisama.com.br",
      lang: "pt-br",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd 'de' MMMM 'de' yyyy",
      dateFormatLocale: "pt-BR",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "KlikManga",
      baseUrl: "https://klikmanga.id",
      lang: "id",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: "id",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "KSGroupScans",
      baseUrl: "https://ksgroupscans.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "LHTranslation",
      baseUrl: "https://lhtranslation.net",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Lolicon",
      baseUrl: "https://lolicon.mobi",
      lang: "en",
      isNsfw: true,
      typeSource: "madara",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Lord Manga",
      baseUrl: "https://lordmanga.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "MangaVisa",
      baseUrl: "https://mangavisa.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "MangaClash",
      baseUrl: "https://mangaclash.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MM/dd/yy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Manga District",
      baseUrl: "https://mangadistrict.com",
      lang: "tr",
      typeSource: "madara",
      iconUrl: '',
      isNsfw: true,
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Manga-fast.com",
      baseUrl: "https://manga-fast.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "d MMMM'،' yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Manga Fenix",
      baseUrl: "https://manga-fenix.com",
      lang: "es",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: "es",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "MangaFreak.online",
      baseUrl: "https://mangafreak.online",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "d MMMM، yyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "MangaGreat",
      baseUrl: "https://mangagreat.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Manga Hentai",
      baseUrl: "https://mangahentai.me",
      lang: "en",
      isNsfw: true,
      typeSource: "madara",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "MangaMe",
      baseUrl: "https://mangame.org",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd.MM.yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Manga One Love",
      baseUrl: "https://mangaonelove.site",
      lang: "ru",
      typeSource: "madara",
      iconUrl: '',
      isNsfw: true,
      dateFormat: "dd.MM.yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Manga Read",
      baseUrl: "https://mangaread.co",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "yyyy-MM-dd",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "MangaRolls",
      baseUrl: "https://mangarolls.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Manga Şehri",
      baseUrl: "https://mangasehri.com",
      lang: "tr",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd/MM/yyy",
      dateFormatLocale: "tr",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Mangasushi",
      baseUrl: "https://mangasushi.org",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Manhwa68",
      baseUrl: "https://manhwa68.com",
      lang: "en",
      isNsfw: true,
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Manhwua.fans",
      baseUrl: "https://manhwua.fans",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "yyyy'年'M'月'd",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "ManyToon.me",
      baseUrl: "https://manytoon.me",
      lang: "en",
      isNsfw: true,
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Milftoon",
      baseUrl: "https://milftoon.xxx",
      lang: "en",
      isNsfw: true,
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "d MMMM, yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "MurimScan",
      baseUrl: "https://murimscan.run",
      lang: "en",
      isNsfw: true,
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Ninja Scan",
      baseUrl: "https://ninjascan.xyz",
      lang: "pt-br",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd 'de' MMMMM 'de' yyyy",
      dateFormatLocale: "pt-BR",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "NovelCrow",
      baseUrl: "https://novelcrow.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      isNsfw: true,
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Pirulito Rosa",
      baseUrl: "https://pirulitorosa.site",
      lang: "pt-br",
      typeSource: "madara",
      iconUrl: '',
      isNsfw: true,
      dateFormat: "dd/MM/yyy",
      dateFormatLocale: "pt-BR",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "RagnarokScan",
      baseUrl: "https://ragnarokscan.com",
      lang: "es",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMMMM dd, yyyy",
      dateFormatLocale: "es",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Ragnarok Scanlation",
      baseUrl: "https://ragnarokscanlation.com",
      lang: "es",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: "es",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Rio2 Manga",
      baseUrl: "https://rio2manga.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Romantik Manga",
      baseUrl: "https://rio2manga.com",
      lang: "tr",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "SamuraiScan",
      baseUrl: "https://samuraiscan.com",
      lang: "es",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: "es",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Sdl scans",
      baseUrl: "https://sdlscans.com",
      lang: "es",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMMMM dd, yyyy",
      dateFormatLocale: "es",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Shayami",
      baseUrl: "https://shayami.com",
      lang: "es",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMM d, yyy",
      dateFormatLocale: "es",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Taurus Fansub",
      baseUrl: "https://tatakaescan.com",
      lang: "es",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd/MM/yyy",
      dateFormatLocale: "es",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "The Sugar",
      baseUrl: "https://thesugarscan.com",
      lang: "pt-br",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd/MM/yyyy",
      dateFormatLocale: "pt-BR",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "365Manga",
      baseUrl: "https://365manga.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Tortuga Ceviri",
      baseUrl: "https://tortuga-ceviri.com",
      lang: "tr",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: "tr",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Tumangaonline.site",
      baseUrl: "https://tumangaonline.site",
      lang: "es",
      isNsfw: true,
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd MMMMM, yyyy",
      dateFormatLocale: "es",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Winter Scan",
      baseUrl: "https://winterscan.com",
      lang: "pt-br",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd 'de' MMMM 'de' yyyy",
      dateFormatLocale: "pt-BR",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Yuri Verso",
      baseUrl: "https://yuri.live",
      lang: "pt-br",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd/MM/yyyy",
      dateFormatLocale: "pt-BR",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Zero Scan",
      baseUrl: "https://zeroscan.com.br",
      lang: "pt-br",
      isNsfw: true,
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd/MM/yyyy",
      dateFormatLocale: "pt-BR",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "مانجا ليك",
      baseUrl: "https://mangalek.com",
      lang: "ar",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: "ar",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
];
