import '../../model/source.dart';

const madaraVersion = "0.0.11";
const madaraSourceCodeUrl =
    "https://raw.githubusercontent.com/kodjodevf/mangayomi-extensions/main/multisrc/madara/madara-v$madaraVersion.dart";
const defaultDateFormat = "MMMM dd, yyyy";
const defaultDateFormatLocale = "en_US";
List<Source> get madaraSourcesList => _madaraSourcesList;
List<Source> _madaraSourcesList = [
  Source(
      name: "FR-Scan",
      baseUrl: "https://fr-scan.com",
      lang: "fr",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: "fr",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "AstralManga",
      baseUrl: "https://astral-manga.fr",
      lang: "fr",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd/mm/yyyy",
      dateFormatLocale: "fr",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Akuma no Tenshi",
      baseUrl: "https://akumanotenshi.com",
      lang: "tr",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd/MM/yyyy",
      dateFormatLocale: "pt-BR",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Adult Webtoon",
      baseUrl: "https://adultwebtoon.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      isNsfw: true,
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "ArazNovel",
      baseUrl: "https://www.araznovel.com",
      lang: "tr",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "d MMMM yyyy",
      dateFormatLocale: "en",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "BestManga",
      baseUrl: "https://bestmanga.club",
      lang: "ru",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd.MM.yyyy",
      dateFormatLocale: "ru",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Chibi Manga",
      baseUrl: "https://www.cmreader.info",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "EvaScans",
      baseUrl: "https://evascans.com",
      lang: "tr",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMM d, yyy",
      dateFormatLocale: "tr",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Final Scans",
      baseUrl: "https://finalscans.com",
      lang: "pt-br",
      typeSource: "madara",
      iconUrl: '',
      isNsfw: true,
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: "pt-BR",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Glory Manga",
      baseUrl: "https://glorymanga.com",
      lang: "tr",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd/MM/yyy",
      dateFormatLocale: "tr",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),

  Source(
      name: "Its Your Right Manhua",
      baseUrl: "https://itsyourightmanhua.com/",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Kami Sama Explorer",
      baseUrl: "https://leitor.kamisama.com.br",
      lang: "pt-br",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd 'de' MMMM 'de' yyyy",
      dateFormatLocale: "pt-BR",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "KSGroupScans",
      baseUrl: "https://ksgroupscans.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "LHTranslation",
      baseUrl: "https://lhtranslation.net",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Lolicon",
      baseUrl: "https://lolicon.mobi",
      lang: "en",
      isNsfw: true,
      typeSource: "madara",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "MangaVisa",
      baseUrl: "https://mangavisa.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Manga District",
      baseUrl: "https://mangadistrict.com",
      lang: "tr",
      typeSource: "madara",
      iconUrl: '',
      isNsfw: true,
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "MangaFreak.online",
      baseUrl: "https://mangafreak.online",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "d MMMM، yyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "MangaGreat",
      baseUrl: "https://mangagreat.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Manga Read",
      baseUrl: "https://mangaread.co",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "yyyy-MM-dd",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "MangaRolls",
      baseUrl: "https://mangarolls.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Manga Şehri",
      baseUrl: "https://mangasehri.com",
      lang: "tr",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd/MM/yyy",
      dateFormatLocale: "tr",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Mangasushi",
      baseUrl: "https://mangasushi.org",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Manhwa68",
      baseUrl: "https://manhwa68.com",
      lang: "en",
      isNsfw: true,
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Milftoon",
      baseUrl: "https://milftoon.xxx",
      lang: "en",
      isNsfw: true,
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "d MMMM, yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "NovelCrow",
      baseUrl: "https://novelcrow.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      isNsfw: true,
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
 
  Source(
      name: "Rio2 Manga",
      baseUrl: "https://rio2manga.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Romantik Manga",
      baseUrl: "https://rio2manga.com",
      lang: "tr",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Taurus Fansub",
      baseUrl: "https://tatakaescan.com",
      lang: "es",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd/MM/yyy",
      dateFormatLocale: "es",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Tortuga Ceviri",
      baseUrl: "https://tortuga-ceviri.com",
      lang: "tr",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: "tr",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Yuri Verso",
      baseUrl: "https://yuri.live",
      lang: "pt-br",
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd/MM/yyyy",
      dateFormatLocale: "pt-BR",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Zero Scan",
      baseUrl: "https://zeroscan.com.br",
      lang: "pt-br",
      isNsfw: true,
      typeSource: "madara",
      iconUrl: '',
      dateFormat: "dd/MM/yyyy",
      dateFormatLocale: "pt-BR",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
];
