import '../../../model/source.dart';

const apiUrl = 'https://api.mangadex.org';
const baseUrl = 'https://mangadex.org';
const isNsfw = true;
const mangadexVersion = "0.0.11";
const mangadexSourceCodeUrl =
    "https://raw.githubusercontent.com/kodjodevf/mangayomi-extensions/main/src/all/mangadex/mangadex-v$mangadexVersion.dart";
const iconUrl = '';
List<Source> get mangaDexSourcesList => _mangaDexSourcesList;
List<Source> _mangaDexSourcesList = [
  Source(
      name: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'en',
      typeSource: "mangadex",
      iconUrl: iconUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us',
      version: mangadexVersion,
      sourceCodeUrl: mangadexSourceCodeUrl),
  Source(
      name: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'ar',
      typeSource: "mangadex",
      iconUrl: iconUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us',
      version: mangadexVersion,
      sourceCodeUrl: mangadexSourceCodeUrl),
  Source(
      name: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'pt',
      typeSource: "mangadex",
      iconUrl: iconUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us',
      version: mangadexVersion,
      sourceCodeUrl: mangadexSourceCodeUrl),
  Source(
      name: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'pt-br',
      typeSource: "mangadex",
      iconUrl: iconUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us',
      version: mangadexVersion,
      sourceCodeUrl: mangadexSourceCodeUrl),
  Source(
      name: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'it',
      typeSource: "mangadex",
      iconUrl: iconUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us',
      version: mangadexVersion,
      sourceCodeUrl: mangadexSourceCodeUrl),
  Source(
      name: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'ru',
      typeSource: "mangadex",
      iconUrl: iconUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us',
      version: mangadexVersion,
      sourceCodeUrl: mangadexSourceCodeUrl),
  Source(
      name: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'es',
      typeSource: "mangadex",
      iconUrl: iconUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us',
      version: mangadexVersion,
      sourceCodeUrl: mangadexSourceCodeUrl),
  Source(
      name: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'es-419',
      typeSource: "mangadex",
      iconUrl: iconUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us',
      version: mangadexVersion,
      sourceCodeUrl: mangadexSourceCodeUrl),
  Source(
      name: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'id',
      typeSource: "mangadex",
      iconUrl: iconUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us',
      version: mangadexVersion,
      sourceCodeUrl: mangadexSourceCodeUrl),
  Source(
      name: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'hi',
      typeSource: "mangadex",
      iconUrl: iconUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us',
      version: mangadexVersion,
      sourceCodeUrl: mangadexSourceCodeUrl),
  Source(
      name: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'de',
      typeSource: "mangadex",
      iconUrl: iconUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us',
      version: mangadexVersion,
      sourceCodeUrl: mangadexSourceCodeUrl),
  Source(
      name: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'ja',
      typeSource: "mangadex",
      iconUrl: iconUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us',
      version: mangadexVersion,
      sourceCodeUrl: mangadexSourceCodeUrl),
  Source(
      name: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'tr',
      typeSource: "mangadex",
      iconUrl: iconUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us',
      version: mangadexVersion,
      sourceCodeUrl: mangadexSourceCodeUrl),
  Source(
      name: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'pl',
      typeSource: "mangadex",
      iconUrl: iconUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us',
      version: mangadexVersion,
      sourceCodeUrl: mangadexSourceCodeUrl),
  Source(
      name: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'zh',
      typeSource: "mangadex",
      iconUrl: iconUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us',
      version: mangadexVersion,
      sourceCodeUrl: mangadexSourceCodeUrl),
  Source(
      name: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'zh-hk',
      typeSource: "mangadex",
      iconUrl: iconUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us',
      version: mangadexVersion,
      sourceCodeUrl: mangadexSourceCodeUrl),
  Source(
      name: 'MangaDex',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'fr',
      typeSource: "mangadex",
      iconUrl: iconUrl,
      dateFormat: "yyyy-MM-dd'T'HH:mm:ss+SSS",
      isNsfw: isNsfw,
      dateFormatLocale: 'en_Us',
      version: mangadexVersion,
      sourceCodeUrl: mangadexSourceCodeUrl),
];
