import '../../../model/source.dart';

const comickVersion = "0.0.1";
const comickSourceCodeUrl =
    "https://raw.githubusercontent.com/kodjodevf/mangayomi-extensions/main/src/all/comick/comick-v$comickVersion.dart";

const defaultDateFormat = "yyyy-MM-dd'T'HH:mm:ss'Z'";
const defaultDateFormatLocale = "en";

const iconUrl =
    'https://comick.app/_next/image?url=%2Fstatic%2Ficons%2Funicorn-64.png&w=144&q=75';
const apiUrl = 'https://api.comick.fun';
const baseUrl = 'https://comick.app';
const isNsfw = true;
List<Source> get comickSourcesList => _comickSourcesList;
List<Source> _comickSourcesList = [
  Source(
      name: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'en',
      typeSource: "comick",
      iconUrl: iconUrl,
      dateFormat: defaultDateFormat,
      isNsfw: isNsfw,
      dateFormatLocale: defaultDateFormatLocale,
      version: comickVersion,
      sourceCodeUrl: comickSourceCodeUrl),
  Source(
      name: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'ar',
      typeSource: "comick",
      iconUrl: iconUrl,
      dateFormat: defaultDateFormat,
      isNsfw: isNsfw,
      dateFormatLocale: defaultDateFormatLocale,
      version: comickVersion,
      sourceCodeUrl: comickSourceCodeUrl),
  Source(
      name: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'pt',
      typeSource: "comick",
      iconUrl: iconUrl,
      dateFormat: defaultDateFormat,
      isNsfw: isNsfw,
      dateFormatLocale: defaultDateFormatLocale,
      version: comickVersion,
      sourceCodeUrl: comickSourceCodeUrl),
  Source(
      name: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'pt-br',
      typeSource: "comick",
      iconUrl: iconUrl,
      dateFormat: defaultDateFormat,
      isNsfw: isNsfw,
      dateFormatLocale: defaultDateFormatLocale,
      version: comickVersion,
      sourceCodeUrl: comickSourceCodeUrl),
  Source(
      name: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'it',
      typeSource: "comick",
      iconUrl: iconUrl,
      dateFormat: defaultDateFormat,
      isNsfw: isNsfw,
      dateFormatLocale: defaultDateFormatLocale,
      version: comickVersion,
      sourceCodeUrl: comickSourceCodeUrl),
  Source(
      name: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'ru',
      typeSource: "comick",
      iconUrl: iconUrl,
      dateFormat: defaultDateFormat,
      isNsfw: isNsfw,
      dateFormatLocale: defaultDateFormatLocale,
      version: comickVersion,
      sourceCodeUrl: comickSourceCodeUrl),
  Source(
      name: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'es',
      typeSource: "comick",
      iconUrl: iconUrl,
      dateFormat: defaultDateFormat,
      isNsfw: isNsfw,
      dateFormatLocale: defaultDateFormatLocale,
      version: comickVersion,
      sourceCodeUrl: comickSourceCodeUrl),
  Source(
      name: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'es-419',
      typeSource: "comick",
      iconUrl: iconUrl,
      dateFormat: defaultDateFormat,
      isNsfw: isNsfw,
      dateFormatLocale: defaultDateFormatLocale,
      version: comickVersion,
      sourceCodeUrl: comickSourceCodeUrl),
  Source(
      name: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'id',
      typeSource: "comick",
      iconUrl: iconUrl,
      dateFormat: defaultDateFormat,
      isNsfw: isNsfw,
      dateFormatLocale: defaultDateFormatLocale,
      version: comickVersion,
      sourceCodeUrl: comickSourceCodeUrl),
  Source(
      name: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'hi',
      typeSource: "comick",
      iconUrl: iconUrl,
      dateFormat: defaultDateFormat,
      isNsfw: isNsfw,
      dateFormatLocale: defaultDateFormatLocale,
      version: comickVersion,
      sourceCodeUrl: comickSourceCodeUrl),
  Source(
      name: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'de',
      typeSource: "comick",
      iconUrl: iconUrl,
      dateFormat: defaultDateFormat,
      isNsfw: isNsfw,
      dateFormatLocale: defaultDateFormatLocale,
      version: comickVersion,
      sourceCodeUrl: comickSourceCodeUrl),
  Source(
      name: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'ja',
      typeSource: "comick",
      iconUrl: iconUrl,
      dateFormat: defaultDateFormat,
      isNsfw: isNsfw,
      dateFormatLocale: defaultDateFormatLocale,
      version: comickVersion,
      sourceCodeUrl: comickSourceCodeUrl),
  Source(
      name: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'tr',
      typeSource: "comick",
      iconUrl: iconUrl,
      dateFormat: defaultDateFormat,
      isNsfw: isNsfw,
      dateFormatLocale: defaultDateFormatLocale,
      version: comickVersion,
      sourceCodeUrl: comickSourceCodeUrl),
  Source(
      name: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'pl',
      typeSource: "comick",
      iconUrl: iconUrl,
      dateFormat: defaultDateFormat,
      isNsfw: isNsfw,
      dateFormatLocale: defaultDateFormatLocale,
      version: comickVersion,
      sourceCodeUrl: comickSourceCodeUrl),
  Source(
      name: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'zh',
      typeSource: "comick",
      iconUrl: iconUrl,
      dateFormat: defaultDateFormat,
      isNsfw: isNsfw,
      dateFormatLocale: defaultDateFormatLocale,
      version: comickVersion,
      sourceCodeUrl: comickSourceCodeUrl),
  Source(
      name: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'zh-hk',
      typeSource: "comick",
      iconUrl: iconUrl,
      dateFormat: defaultDateFormat,
      isNsfw: isNsfw,
      dateFormatLocale: defaultDateFormatLocale,
      version: comickVersion,
      sourceCodeUrl: comickSourceCodeUrl),
  Source(
      name: 'Comick',
      apiUrl: apiUrl,
      baseUrl: baseUrl,
      lang: 'fr',
      typeSource: "comick",
      iconUrl: iconUrl,
      dateFormat: defaultDateFormat,
      isNsfw: isNsfw,
      dateFormatLocale: defaultDateFormatLocale,
      version: comickVersion,
      sourceCodeUrl: comickSourceCodeUrl),
];
