import '../../../model/source.dart';
import '../../../utils/utils.dart';

const madaraVersion = "0.0.12";
const madaraSourceCodeUrl =
    "https://raw.githubusercontent.com/kodjodevf/mangayomi-extensions/main/manga/multisrc/madara/madara-v$madaraVersion.dart";
const defaultDateFormat = "MMMM dd, yyyy";
const defaultDateFormatLocale = "en_US";

List<Source> get madaraSourcesList => _madaraSourcesList;
List<Source> _madaraSourcesList = [
  Source(
      name: "FR-Scan",
      baseUrl: "https://fr-scan.com",
      lang: "fr",
      typeSource: "madara",
      iconUrl: getIconUrl("frscan", "fr"),
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: "fr",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "AstralManga",
      baseUrl: "https://astral-manga.fr",
      lang: "fr",
      typeSource: "madara",
      iconUrl: getIconUrl("astralmanga", "fr"),
      dateFormat: "dd/mm/yyyy",
      dateFormatLocale: "fr",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Akuma no Tenshi",
      baseUrl: "https://akumanotenshi.com",
      lang: "pt-BR",
      typeSource: "madara",
      iconUrl: getIconUrl("akumanotenshi", "pt"),
      dateFormat: "dd/MM/yyyy",
      dateFormatLocale: "pt-BR",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Adult Webtoon",
      baseUrl: "https://adultwebtoon.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: getIconUrl("adultwebtoon", "en"),
      isNsfw: true,
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "ArazNovel",
      baseUrl: "https://www.araznovel.com",
      lang: "tr",
      typeSource: "madara",
      iconUrl: getIconUrl("araznovel", "tr"),
      dateFormat: "d MMMM yyyy",
      dateFormatLocale: "en",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "BestManga",
      baseUrl: "https://bestmanga.club",
      lang: "ru",
      typeSource: "madara",
      iconUrl: getIconUrl("bestmanga", "ru"),
      dateFormat: "dd.MM.yyyy",
      dateFormatLocale: "ru",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Chibi Manga",
      baseUrl: "https://www.cmreader.info",
      lang: "en",
      typeSource: "madara",
      iconUrl: getIconUrl("chibimanga", "en"),
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "EvaScans",
      baseUrl: "https://evascans.com",
      lang: "tr",
      typeSource: "madara",
      iconUrl: getIconUrl("evascans", "tr"),
      dateFormat: "MMM d, yyy",
      dateFormatLocale: "tr",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Final Scans",
      baseUrl: "https://finalscans.com",
      lang: "pt-br",
      typeSource: "madara",
      iconUrl: getIconUrl("finalscans", "pt"),
      isNsfw: true,
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: "pt-BR",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Glory Manga",
      baseUrl: "https://glorymanga.com",
      lang: "tr",
      typeSource: "madara",
      iconUrl: getIconUrl("glorymanga", "tr"),
      dateFormat: "dd/MM/yyy",
      dateFormatLocale: "tr",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Its Your Right Manhua",
      baseUrl: "https://itsyourightmanhua.com/",
      lang: "en",
      typeSource: "madara",
      iconUrl: getIconUrl("", ""),
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Kami Sama Explorer",
      baseUrl: "https://leitor.kamisama.com.br",
      lang: "pt-br",
      typeSource: "madara",
      iconUrl: getIconUrl("kamisamaexplorer", "pt"),
      dateFormat: "dd 'de' MMMM 'de' yyyy",
      dateFormatLocale: "pt-BR",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "KSGroupScans",
      baseUrl: "https://ksgroupscans.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: getIconUrl("ksgroupscans", "en"),
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "LHTranslation",
      baseUrl: "https://lhtranslation.net",
      lang: "en",
      typeSource: "madara",
      iconUrl: getIconUrl("lhtranslation", "en"),
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Lolicon",
      baseUrl: "https://lolicon.mobi",
      lang: "en",
      isNsfw: true,
      typeSource: "madara",
      iconUrl: getIconUrl("lolicon", "en"),
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "MangaVisa",
      baseUrl: "https://mangavisa.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: getIconUrl("", ""),
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Manga District",
      baseUrl: "https://mangadistrict.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: getIconUrl("mangadistrict", "en"),
      isNsfw: true,
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "MangaFreak.online",
      baseUrl: "https://mangafreak.online",
      lang: "en",
      typeSource: "madara",
      iconUrl: getIconUrl("mangafreakonline", "en"),
      dateFormat: "d MMMM، yyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "MangaGreat",
      baseUrl: "https://mangagreat.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: getIconUrl("mangagreat", "en"),
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Manga Read",
      baseUrl: "https://mangaread.co",
      lang: "en",
      typeSource: "madara",
      iconUrl: getIconUrl("mangaread", "en"),
      dateFormat: "yyyy-MM-dd",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "MangaRolls",
      baseUrl: "https://mangarolls.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: getIconUrl("mangarolls", "en"),
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Manga Şehri",
      baseUrl: "https://mangasehri.com",
      lang: "tr",
      typeSource: "madara",
      iconUrl: getIconUrl("mangasehri", "tr"),
      dateFormat: "dd/MM/yyy",
      dateFormatLocale: "tr",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Mangasushi",
      baseUrl: "https://mangasushi.org",
      lang: "en",
      typeSource: "madara",
      iconUrl: getIconUrl("mangasushi", "en"),
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Manhwa68",
      baseUrl: "https://manhwa68.com",
      lang: "en",
      isNsfw: true,
      typeSource: "madara",
      iconUrl: getIconUrl("manhwa68", "en"),
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Milftoon",
      baseUrl: "https://milftoon.xxx",
      lang: "en",
      isNsfw: true,
      typeSource: "madara",
      iconUrl: getIconUrl("milftoon", "en"),
      dateFormat: "d MMMM, yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "NovelCrow",
      baseUrl: "https://novelcrow.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: getIconUrl("novelcrow", "en"),
      isNsfw: true,
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Rio2 Manga",
      baseUrl: "https://rio2manga.com",
      lang: "en",
      typeSource: "madara",
      iconUrl: getIconUrl("rio2manga", "en"),
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Romantik Manga",
      baseUrl: "https://romantikmanga.com",
      lang: "tr",
      typeSource: "madara",
      iconUrl: getIconUrl("romantikmanga", "tr"),
      dateFormat: "MMM d, yyy",
      dateFormatLocale: "tr",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Taurus Fansub",
      baseUrl: "https://taurusfansub.com",
      lang: "es",
      typeSource: "madara",
      iconUrl: getIconUrl("taurusfansub", "es"),
      dateFormat: "dd/MM/yyy",
      dateFormatLocale: "es",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Tatakae Scan",
      baseUrl: "https://tatakaescan.com",
      lang: "pt-BR",
      typeSource: "madara",
      iconUrl: getIconUrl("tatakaescan", "pt"),
      dateFormat: "dd 'de' MMMMM 'de' yyyy",
      dateFormatLocale: "pt-BR",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Tortuga Ceviri",
      baseUrl: "https://tortuga-ceviri.com",
      lang: "tr",
      typeSource: "madara",
      iconUrl: getIconUrl("tortugaceviri", "tr"),
      dateFormat: "MMMM d, yyyy",
      dateFormatLocale: "tr",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Yuri Verso",
      baseUrl: "https://yuri.live",
      lang: "pt-br",
      typeSource: "madara",
      iconUrl: getIconUrl("yuriverso", "pt"),
      dateFormat: "dd/MM/yyyy",
      dateFormatLocale: "pt-BR",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
  Source(
      name: "Zero Scan",
      baseUrl: "https://zeroscan.com.br",
      lang: "pt-br",
      isNsfw: true,
      typeSource: "madara",
      iconUrl: getIconUrl("zeroscan", "pt"),
      dateFormat: "dd/MM/yyyy",
      dateFormatLocale: "pt-BR",
      version: madaraVersion,
      sourceCodeUrl: madaraSourceCodeUrl),
];
