import '../../model/source.dart';

const mangareaderVersion = "0.0.1";
const mangareaderSourceCodeUrl =
    "https://raw.githubusercontent.com/kodjodevf/mangayomi-extensions/main/multisrc/mangareader/mangareader-v$mangareaderVersion.dart";
const defaultDateFormat = "MMMM dd, yyyy";
const defaultDateFormatLocale = "en_US";
List<Source> get mangareaderSourcesList => _mangareaderSourcesList;
List<Source> _mangareaderSourcesList = [
  Source(
      name: "Asura Scans",
      baseUrl: "https://www.asurascans.com",
      lang: "en",
      iconUrl: '',
      dateFormat: "MMM d, yyyy",
      dateFormatLocale: "en_US",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Legacy Scans",
      baseUrl: "https://legacy-scans.com",
      lang: "fr",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      hasCloudflare: true,
      dateFormatLocale: "fr",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Komik Lab",
      baseUrl: "https://komiklab.com",
      lang: "en",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Miau Scan",
      baseUrl: "https://miauscan.com",
      lang: "pt-BR",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Animated Glitched Scans",
      baseUrl: "https://anigliscans.com",
      lang: "en",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Arena Scans",
      baseUrl: "https://arenascans.net",
      lang: "en",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Azure Scans",
      baseUrl: "https://azuremanga.com",
      lang: "en",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Banana-Scan",
      baseUrl: "https://banana-scan.com",
      lang: "fr",
      isNsfw: true,
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: "fr",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Boosei",
      baseUrl: "https://boosei.net",
      lang: "id",
      iconUrl: '',
      hasCloudflare: true,
      dateFormat: defaultDateFormat,
      dateFormatLocale: "id",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Babel Wuxia",
      baseUrl: "https://babelwuxia.com",
      lang: "en",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  // Source(
  //     name: "Cartel de Manhwas",
  //     baseUrl: "https://carteldemanhwas.com",
  //     lang: "es",
  //     iconUrl: '',
  //     dateFormat: defaultDateFormat,
  //     dateFormatLocale: defaultDateFormatLocale,
  //     version: mangareaderVersion,
  //     sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Clayrer",
      baseUrl: "https://clayrer.net",
      lang: "es",
      iconUrl: '',
      dateFormat: "MMM d, yyyy",
      dateFormatLocale: "es",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Constellar Scans",
      baseUrl: "https://constellarscans.com",
      lang: "en",
      isNsfw: true,
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Cosmic Scans",
      baseUrl: "https://cosmicscans.com",
      lang: "en",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "CosmicScans.id",
      baseUrl: "https://cosmicscans.id",
      lang: "id",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Diskus Scan",
      baseUrl: "https://diskusscan.com",
      lang: "pt-BR",
      iconUrl: '',
      dateFormat: "MMMMM dd, yyyy",
      dateFormatLocale: "pt-BR",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Dojing.net",
      baseUrl: "https://dojing.net",
      lang: "id",
      isNsfw: true,
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "DragonTranslation",
      baseUrl: "https://dragontranslation.com",
      lang: "es",
      isNsfw: true,
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "DuniaKomik.id",
      baseUrl: "https://duniakomik.id",
      lang: "id",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: "id",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "ElarcPage",
      baseUrl: "https://elarcpage.com",
      lang: "en",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Epsilon Scan",
      baseUrl: "https://epsilonscan.fr",
      lang: "fr",
      isNsfw: true,
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: "fr",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Franxx Mangás",
      baseUrl: "https://franxxmangas.net",
      lang: "pt-BR",
      isNsfw: true,
      iconUrl: '',
      dateFormat: "MMMMM dd, yyyy",
      dateFormatLocale: "pt-BR",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Gecenin Lordu",
      baseUrl: "https://geceninlordu.com",
      lang: "tr",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "GoGoManga",
      baseUrl: "https://gogomanga.fun",
      lang: "en",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Gremory Mangas",
      baseUrl: "https://gremorymangas.com",
      lang: "es",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Hanuman Scan",
      baseUrl: "https://hanumanscan.com",
      lang: "en",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Heroxia",
      baseUrl: "https://heroxia.com",
      lang: "id",
      isNsfw: true,
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Imagine Scan",
      baseUrl: "https://imaginescan.com.br",
      lang: "pt-BR",
      isNsfw: true,
      iconUrl: '',
      dateFormat: "MMMMM dd, yyyy",
      dateFormatLocale: "pt-BR",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Infernal Void Scans",
      baseUrl: "https://void-scans.com",
      lang: "en",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "KataKomik",
      baseUrl: "https://katakomik.online",
      lang: "id",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Komik Seru",
      baseUrl: "https://komikseru.me",
      lang: "id",
      isNsfw: true,
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Kanzenin",
      baseUrl: "https://kanzenin.xyz",
      lang: "id",
      isNsfw: true,
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "KomikSan",
      baseUrl: "https://komiksan.ml",
      lang: "id",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Kiryuu",
      baseUrl: "https://kiryuu.id",
      lang: "id",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: "id",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Komik AV",
      baseUrl: "https://komikav.com",
      lang: "id",
      iconUrl: '',
      hasCloudflare: true,
      dateFormat: defaultDateFormat,
      dateFormatLocale: "id",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Komik Station",
      baseUrl: "https://komikstation.co",
      lang: "id",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      hasCloudflare: true,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "KomikMama",
      baseUrl: "https://komikmama.co",
      lang: "id",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: "id",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "KumaPoi",
      baseUrl: "https://kumapoi.club",
      lang: "id",
      isNsfw: true,
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: "id",
      hasCloudflare: true,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Komiku.com",
      baseUrl: "https://komiku.com",
      lang: "id",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: "id",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Kuma Scans (Kuma Translation)",
      baseUrl: "https://kumascans.com",
      lang: "en",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      hasCloudflare: true,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Legacy Scans",
      baseUrl: "https://legacy-scans.com",
      lang: "fr",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "LianScans",
      baseUrl: "https://www.lianscans.my.id",
      lang: "id",
      isNsfw: true,
      iconUrl: '',
      dateFormat: defaultDateFormat,
      hasCloudflare: true,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Magus Manga",
      baseUrl: "https://magusmanga.com",
      lang: "ar",
      iconUrl: '',
      dateFormat: "MMMMM d, yyyy",
      dateFormatLocale: "ar",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Manga Indo.me",
      baseUrl: "https://mangaindo.me",
      lang: "id",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Manga Raw.org",
      baseUrl: "https://mangaraw.org",
      lang: "ja",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Mangacim",
      baseUrl: "https://www.mangacim.com",
      lang: "tr",
      iconUrl: '',
      dateFormat: "MMM d, yyy",
      dateFormatLocale: "tr",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "MangaKita",
      baseUrl: "https://mangakita.net",
      lang: "id",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "MangaTale",
      baseUrl: "https://mangatale.co",
      lang: "id",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "MangaWT",
      baseUrl: "https://mangawt.com",
      lang: "tr",
      iconUrl: '',
      dateFormat: "MMM d, yyyy",
      dateFormatLocale: "tr",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Mangayaro",
      baseUrl: "https://mangayaro.net",
      lang: "id",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      hasCloudflare: true,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Manhwa Lover",
      baseUrl: "https://manhwalover.com",
      lang: "en",
      isNsfw: true,
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "MangaSwat",
      baseUrl: "https://swatop.club/",
      lang: "ar",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Mangás Chan",
      baseUrl: "https://mangaschan.com",
      lang: "pt-BR",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: "pt-br",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Manhwa Freak",
      baseUrl: "https://manhwafreak.com",
      lang: "en",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "ManhwaLand.mom",
      baseUrl: "https://manhwaland.us",
      lang: "id",
      isNsfw: true,
      iconUrl: '',
      dateFormat: defaultDateFormat,
      hasCloudflare: true,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Manhwax",
      baseUrl: "https://manhwax.com",
      lang: "en",
      isNsfw: true,
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Mareceh",
      baseUrl: "https://mareceh.com",
      lang: "id",
      isNsfw: true,
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "MasterKomik",
      baseUrl: "https://masterkomik.com",
      lang: "id",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      hasCloudflare: true,
      dateFormatLocale: "id",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "MELOKOMIK",
      baseUrl: "https://melokomik.xyz",
      lang: "id",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: "id",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Mihentai",
      baseUrl: "https://mihentai.com",
      lang: "all",
      isNsfw: true,
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Mode Scanlator",
      baseUrl: "https://modescanlator.com",
      lang: "pt-BR",
      iconUrl: '',
      dateFormat: "MMMMM dd, yyyy",
      dateFormatLocale: "pt-BR",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Mundo Mangá-Kun",
      baseUrl: "https://mundomangakun.com.br",
      lang: "pt-BR",
      isNsfw: true,
      iconUrl: '',
      dateFormat: "MMMMM dd, yyyy",
      dateFormatLocale: "pt-BR",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Nekomik",
      baseUrl: "https://nekomik.com",
      lang: "id",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      hasCloudflare: true,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Ngomik",
      baseUrl: "https://ngomik.net",
      lang: "id",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Nocturnal Scans",
      baseUrl: "https://nocturnalscans.com",
      lang: "en",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Origami Orpheans",
      baseUrl: "https://origami-orpheans.com.br",
      lang: "pt-BR",
      iconUrl: '',
      dateFormat: "MMMMM dd, yyyy",
      dateFormatLocale: "pt-BR",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Ozul Scans",
      baseUrl: "https://ozulscans.com",
      lang: "ar",
      iconUrl: '',
      dateFormat: "MMM d, yyy",
      dateFormatLocale: "ar",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Patatescans",
      baseUrl: "https://patatescans.com",
      lang: "fr",
      isNsfw: true,
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Phantom Scans",
      baseUrl: "https://phantomscans.com",
      lang: "en",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "PhenixScans",
      baseUrl: "https://phenixscans.fr",
      lang: "fr",
      iconUrl: '',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "fr",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Pi Scans",
      baseUrl: "https://piscans.in",
      lang: "id",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "PMScans",
      baseUrl: "https://rackusreads.com",
      lang: "en",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Raiki Scan",
      baseUrl: "https://raikiscan.com",
      lang: "es",
      iconUrl: '',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Raven Scans",
      baseUrl: "https://ravenscans.com",
      lang: "en",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Rawkuma",
      baseUrl: "https://rawkuma.com/",
      lang: "ja",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      hasCloudflare: true,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Readkomik",
      baseUrl: "https://readkomik.com",
      lang: "en",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      hasCloudflare: true,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Ryukonesia",
      baseUrl: "https://ryukonesia.net",
      lang: "id",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      hasCloudflare: true,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Sekaikomik",
      baseUrl: "https://www.sekaikomik.pro",
      lang: "id",
      isNsfw: true,
      iconUrl: '',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "id",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Sekte Doujin",
      baseUrl: "https://sektedoujin.lol",
      lang: "id",
      isNsfw: true,
      iconUrl: '',
      dateFormat: "MMMM dd, yyyy",
      hasCloudflare: true,
      dateFormatLocale: "id",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Senpai Ediciones",
      baseUrl: "http://senpaiediciones.com",
      lang: "es",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Shadow Mangas",
      baseUrl: "https://shadowmangas.com",
      lang: "es",
      iconUrl: '',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "es",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Shea Manga",
      baseUrl: "https://sheakomik.com",
      lang: "id",
      iconUrl: '',
      dateFormat: "MMMM dd, yyyy",
      hasCloudflare: true,
      dateFormatLocale: "id",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Silence Scan",
      baseUrl: "https://silencescan.com.br",
      lang: "pt-BR",
      isNsfw: true,
      iconUrl: '',
      dateFormat: "MMMMM dd, yyyy",
      dateFormatLocale: "pt-BR",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Snudae Scans",
      baseUrl: "https://snudaescans.com",
      lang: "en",
      isNsfw: true,
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Summer Fansub",
      baseUrl: "https://smmr.in",
      lang: "pt-BR",
      isNsfw: true,
      iconUrl: '',
      dateFormat: "MMMMM dd, yyyy",
      dateFormatLocale: "pt-BR",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Surya Scans",
      baseUrl: "https://suryascans.com",
      lang: "en",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Sushi-Scan",
      baseUrl: "https://sushiscan.net",
      lang: "fr",
      iconUrl: '',
      dateFormat: "MMMM dd, yyyy",
      hasCloudflare: true,
      dateFormatLocale: "fr",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Tarot Scans",
      baseUrl: "https://www.tarotscans.com",
      lang: "tr",
      iconUrl: '',
      dateFormat: "MMMM dd, yyyy",
      dateFormatLocale: "tr",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "The Apollo Team",
      baseUrl: "https://theapollo.team",
      lang: "en",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Tsundoku Traduções",
      baseUrl: "https://tsundoku.com.br",
      lang: "pt-BR",
      iconUrl: '',
      hasCloudflare: true,
      dateFormat: "MMMMM dd, yyyy",
      dateFormatLocale: "pt-BR",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "TukangKomik",
      baseUrl: "https://tukangkomik.id",
      lang: "id",
      iconUrl: '',
      dateFormat: "MMM d, yyyy",
      dateFormatLocale: "tr",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "TurkToon",
      baseUrl: "https://turktoon.com",
      lang: "tr",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Uzay Manga",
      baseUrl: "https://uzaymanga.com",
      lang: "tr",
      iconUrl: '',
      dateFormat: "MMM d, yyyy",
      dateFormatLocale: "tr",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "Walpurgi Scan",
      baseUrl: "https://www.walpurgiscan.com",
      lang: "it",
      iconUrl: '',
      dateFormat: "MMM d, yyyy",
      dateFormatLocale: "it",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "West Manga",
      baseUrl: "https://westmanga.info",
      lang: "id",
      iconUrl: '',
      hasCloudflare: true,
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "xCaliBR Scans",
      baseUrl: "https://xcalibrscans.com",
      lang: "en",
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: defaultDateFormatLocale,
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
  Source(
      name: "สดใสเมะ",
      baseUrl: "https://www.xn--l3c0azab5a2gta.com",
      lang: "th",
      isNsfw: true,
      iconUrl: '',
      dateFormat: defaultDateFormat,
      dateFormatLocale: "th",
      version: mangareaderVersion,
      sourceCodeUrl: mangareaderSourceCodeUrl),
];
